image: atlassian/default-image:4

test: &test
  step:
    name: Junit Tests
    script:
      - chmod +x ./mvnw
      - ./mvnw package
    services:
      - docker
      -
#Run an integration on a predefined PR. This does not run per default.
integration-test: &integration-test
  step:
    name: Integration Tests
    script:
      - chmod +x ./mvnw
      - ./mvnw package -Dmaven.test.skip
      - npm install -g bats
      - chmod a+x test/*.bats
      - bats test/test.bats
    services:
      - docker

build: &build
  step:
    name: Build Docker Image
    script:
      # build security-scan-runner.jar needed by Dockerfile
      - chmod +x ./mvnw
      - ./mvnw package -Dmaven.test.skip
      # build docker image artifact
      - export IMAGE_NAME=haraleib/${BITBUCKET_REPO_SLUG}
      - export IMAGE_VERSION=pipelines-${BITBUCKET_BUILD_NUMBER}
      - docker build -t $IMAGE_NAME:$IMAGE_VERSION -t $IMAGE_NAME:latest ./docker/
      - docker save --output docker-image.tar.gz $IMAGE_NAME
      - chmod +r docker-image.tar.gz
    services:
      - docker
    artifacts:
      - docker-image.tar.gz

push: &push
  step:
    name: Push Image
    script:
      - pipe: atlassian/bitbucket-pipe-release:5.8.0
        variables:
          REGISTRY_USERNAME: $REGISTRY_USERNAME
          REGISTRY_PASSWORD: $REGISTRY_PASSWORD
          IMAGE: haraleib/$BITBUCKET_REPO_SLUG
          VERSION: 'latest'
          DOCKER_IMAGE_ARCHIVE_FILEPATH: docker-image.tar.gz
          GIT_PUSH: 'false'
    services:
      - docker

pipelines:
  default:
  - <<: *test
  custom:
    integration-test:
    - <<: *integration-test
  branches:
    master:
    - <<: *test
    - <<: *build
    - <<: *push
  #run security-scan on current PR
  pull-requests:
    '**':
      - step:
          name: Security Scan
          script:
            - pipe: docker://haraleib/security-scan:latest
              variables:
                REPOSITORY_ACCESS_TOKEN: ${SECURITY_SCAN_AUTH_TOKEN}
                DEBUG: "true"
